//go:build ignore

// Command gen_tokens projects the canonical design-token set into Go source.
//
// It exists so the TUI never reads the token file at runtime: the canonical set
// stays in docs/ui-ux/design-tokens.json, and the projection is generated,
// checked in and freshness-checked by digest. A generated file that drifts from
// its source fails `tui/theme`'s own test rather than silently rendering stale
// colours.
//
// Run with: go generate ./tui/theme
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

const (
	sourcePath = "../../docs/ui-ux/design-tokens.json"
	outputPath = "tokens_gen.go"
)

type token struct {
	ID        string   `json:"id"`
	Tier      string   `json:"tier"`
	Type      string   `json:"type"`
	Value     string   `json:"value"`
	Platforms []string `json:"platforms"`
	Fallback  string   `json:"capability_fallback"`
	Contrast  *struct {
		Against string  `json:"against"`
		Ratio   float64 `json:"ratio"`
		WCAG    string  `json:"wcag"`
	} `json:"contrast"`
}

type theme struct {
	ID            string            `json:"id"`
	Extends       string            `json:"extends"`
	HighContrast  bool              `json:"high_contrast"`
	ReducedMotion bool              `json:"reduced_motion"`
	Overrides     map[string]string `json:"overrides"`
}

type tokenSet struct {
	Version int      `json:"version"`
	Tiers   []string `json:"tiers"`
	Density []string `json:"density"`
	Tokens  []token  `json:"tokens"`
	Themes  []theme  `json:"themes"`
}

func main() {
	raw, err := os.ReadFile(sourcePath)
	if err != nil {
		fail(err)
	}
	var set tokenSet
	if err := json.Unmarshal(raw, &set); err != nil {
		fail(err)
	}
	sum := sha256.Sum256(raw)
	digest := "sha256:" + hex.EncodeToString(sum[:])[:32]

	sort.Slice(set.Tokens, func(i, j int) bool { return set.Tokens[i].ID < set.Tokens[j].ID })
	sort.Slice(set.Themes, func(i, j int) bool { return set.Themes[i].ID < set.Themes[j].ID })

	var b strings.Builder
	b.WriteString("// Code generated by `go generate ./tui/theme`; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Source: docs/ui-ux/design-tokens.json\n")
	b.WriteString("// Digest: " + digest + "\n\n")
	b.WriteString("package theme\n\n")
	b.WriteString("// sourceDigest identifies the token set this projection was generated from.\n")
	b.WriteString("// TestProjectionMatchesSource recomputes it, so editing the canonical set\n")
	b.WriteString("// without regenerating fails instead of rendering stale values.\n")
	b.WriteString("const sourceDigest = \"" + digest + "\"\n\n")
	b.WriteString("// sourceVersion is the canonical token set version.\n")
	b.WriteString(fmt.Sprintf("const sourceVersion = %d\n\n", set.Version))

	b.WriteString("// declaredTiers is the enforced tier vocabulary, outermost first.\n")
	b.WriteString("var declaredTiers = []string{" + quoteList(set.Tiers) + "}\n\n")

	b.WriteString("// declaredTokens is every token in the canonical set, sorted by ID.\n")
	b.WriteString("var declaredTokens = []tokenDecl{\n")
	for _, t := range set.Tokens {
		b.WriteString("\t{ID: " + quote(t.ID) + ", Tier: " + quote(t.Tier) + ", Kind: " + quote(t.Type) +
			", Value: " + quote(t.Value))
		if len(t.Platforms) > 0 {
			b.WriteString(", Platforms: []string{" + quoteList(t.Platforms) + "}")
		}
		if t.Fallback != "" {
			b.WriteString(", Fallback: " + quote(t.Fallback))
		}
		if t.Contrast != nil {
			b.WriteString(fmt.Sprintf(", Against: %s, Ratio: %g, WCAG: %s",
				quote(t.Contrast.Against), t.Contrast.Ratio, quote(t.Contrast.WCAG)))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("// declaredThemes is every theme, sorted by ID.\n")
	b.WriteString("var declaredThemes = []themeDecl{\n")
	for _, th := range set.Themes {
		b.WriteString("\t{ID: " + quote(th.ID) + ", Extends: " + quote(th.Extends))
		if th.HighContrast {
			b.WriteString(", HighContrast: true")
		}
		if th.ReducedMotion {
			b.WriteString(", ReducedMotion: true")
		}
		if len(th.Overrides) > 0 {
			keys := make([]string, 0, len(th.Overrides))
			for k := range th.Overrides {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			b.WriteString(", Overrides: map[string]string{\n")
			for _, k := range keys {
				b.WriteString("\t\t" + quote(k) + ": " + quote(th.Overrides[k]) + ",\n")
			}
			b.WriteString("\t}")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	// Format in the generator so regenerating can never produce a file that
	// `gofmt -l` flags: a generated file that fails the format gate trains
	// people to ignore the gate.
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(fmt.Errorf("generated source does not parse: %w", err))
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s from %s (%s, %d tokens, %d themes)\n",
		outputPath, sourcePath, digest, len(set.Tokens), len(set.Themes))
}

func quote(s string) string { return fmt.Sprintf("%q", s) }

func quoteList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, v := range values {
		quoted = append(quoted, quote(v))
	}
	return strings.Join(quoted, ", ")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen_tokens:", err)
	os.Exit(1)
}
