// Code generated by `go generate ./tui/theme`; DO NOT EDIT.
//
// Source: docs/ui-ux/design-tokens.json
// Digest: sha256:757d77865bdbf4d0b1a6ffed3bf4077e

package theme

// sourceDigest identifies the token set this projection was generated from.
// TestProjectionMatchesSource recomputes it, so editing the canonical set
// without regenerating fails instead of rendering stale values.
const sourceDigest = "sha256:757d77865bdbf4d0b1a6ffed3bf4077e"

// sourceVersion is the canonical token set version.
const sourceVersion = 1

// declaredTiers is the enforced tier vocabulary, outermost first.
var declaredTiers = []string{"primitive", "semantic", "component"}

// declaredTokens is every token in the canonical set, sorted by ID.
var declaredTokens = []tokenDecl{
	{ID: "token:color.accent", Tier: "semantic", Kind: "color", Value: "token:primitive.blue.500"},
	{ID: "token:color.border-subtle", Tier: "semantic", Kind: "color", Value: "token:primitive.gray.500", Platforms: []string{"tui", "desktop", "web"}},
	{ID: "token:color.error", Tier: "semantic", Kind: "color", Value: "token:primitive.red.500"},
	{ID: "token:color.focus", Tier: "semantic", Kind: "color", Value: "token:primitive.blue.500", Against: "token:color.surface", Ratio: 5.9, WCAG: "AA"},
	{ID: "token:color.panel", Tier: "semantic", Kind: "color", Value: "token:primitive.white", Platforms: []string{"tui", "desktop", "web"}},
	{ID: "token:color.success", Tier: "semantic", Kind: "color", Value: "token:primitive.green.500"},
	{ID: "token:color.surface", Tier: "semantic", Kind: "color", Value: "token:primitive.gray.100", Platforms: []string{"tui", "desktop", "web"}},
	{ID: "token:color.text", Tier: "semantic", Kind: "color", Value: "token:primitive.black", Against: "token:color.surface", Ratio: 16, WCAG: "AAA"},
	{ID: "token:color.text-muted", Tier: "semantic", Kind: "color", Value: "token:primitive.gray.800", Against: "token:color.surface", Ratio: 7, WCAG: "AA"},
	{ID: "token:color.warning", Tier: "semantic", Kind: "color", Value: "token:primitive.amber.500"},
	{ID: "token:primitive.amber.500", Tier: "primitive", Kind: "color", Value: "#b26a00"},
	{ID: "token:primitive.black", Tier: "primitive", Kind: "color", Value: "#000000"},
	{ID: "token:primitive.blue.500", Tier: "primitive", Kind: "color", Value: "#1565c0"},
	{ID: "token:primitive.gray.100", Tier: "primitive", Kind: "color", Value: "#f5f5f5"},
	{ID: "token:primitive.gray.500", Tier: "primitive", Kind: "color", Value: "#808080"},
	{ID: "token:primitive.gray.800", Tier: "primitive", Kind: "color", Value: "#303030"},
	{ID: "token:primitive.green.500", Tier: "primitive", Kind: "color", Value: "#2e7d32"},
	{ID: "token:primitive.motion.fast", Tier: "primitive", Kind: "motion", Value: "80ms"},
	{ID: "token:primitive.radius.1", Tier: "primitive", Kind: "radius", Value: "1"},
	{ID: "token:primitive.red.500", Tier: "primitive", Kind: "color", Value: "#c62828"},
	{ID: "token:primitive.space.1", Tier: "primitive", Kind: "space", Value: "1"},
	{ID: "token:primitive.space.2", Tier: "primitive", Kind: "space", Value: "2"},
	{ID: "token:primitive.space.4", Tier: "primitive", Kind: "space", Value: "4"},
	{ID: "token:primitive.white", Tier: "primitive", Kind: "color", Value: "#ffffff"},
	{ID: "token:tui.approval.prompt", Tier: "component", Kind: "color", Value: "token:color.warning", Platforms: []string{"tui"}},
	{ID: "token:tui.command-palette.highlight", Tier: "component", Kind: "color", Value: "token:color.accent", Platforms: []string{"tui"}},
	{ID: "token:tui.panel.border", Tier: "component", Kind: "border", Value: "token:color.border-subtle", Platforms: []string{"tui"}, Fallback: "ASCII +/- when the terminal lacks Unicode box drawing"},
	{ID: "token:tui.statusline", Tier: "component", Kind: "color", Value: "token:color.panel", Platforms: []string{"tui"}},
}

// declaredThemes is every theme, sorted by ID.
var declaredThemes = []themeDecl{
	{ID: "theme.default", Extends: ""},
	{ID: "theme.high-contrast", Extends: "theme.default", HighContrast: true, Overrides: map[string]string{
		"token:color.text-muted": "token:primitive.black",
	}},
	{ID: "theme.no-color", Extends: "theme.default", Overrides: map[string]string{
		"token:color.accent":        "none",
		"token:color.border-subtle": "none",
		"token:color.error":         "none",
		"token:color.focus":         "none",
		"token:color.panel":         "none",
		"token:color.success":       "none",
		"token:color.surface":       "none",
		"token:color.text":          "none",
		"token:color.text-muted":    "none",
		"token:color.warning":       "none",
	}},
	{ID: "theme.reduced-motion", Extends: "theme.default", ReducedMotion: true, Overrides: map[string]string{
		"token:primitive.motion.fast": "0ms",
	}},
}
