package install

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// AGENTS.md, CLAUDE.md and GEMINI.md belong to the user first. They are the
// conventions a coding agent reads, they usually contain the project's own
// instructions, and the connectors wrote over them without checking — then listed
// the path as created, so the uninstall deleted the file outright. The loss was
// silent and permanent (GAP-141).

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

const userInstructions = "# My project\n\nAlways run the linter before committing.\n"

func TestAUsersInstructionsFileIsNeverOverwritten(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "AGENTS.md")
	write(t, path, userInstructions)

	result, err := WriteManaged(path, Marked("# generated by prumo\n"))
	if err != nil {
		t.Fatal(err)
	}
	if result.Written {
		t.Error("the write was reported as having happened; the user's instructions were destroyed")
	}
	if result.Owned {
		t.Error("a file this framework did not write must never be claimed as owned")
	}
	if result.Skipped == nil {
		t.Fatal("a refusal must say so; a silent skip reads as a successful install")
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != userInstructions {
		t.Fatalf("the file was modified: %q", got)
	}
}

func TestAUsersFileIsNotDeletedByUninstall(t *testing.T) {
	// The half that made the loss permanent: the old path was written, added to
	// the created list, and removed again on uninstall. A manifest that names it
	// is exactly the state a previous version left behind.
	home := t.TempDir()
	root := t.TempDir()
	path := filepath.Join(root, "AGENTS.md")
	write(t, path, userInstructions)

	removed, leftovers := RemoveManagedPaths(home, []string{path})
	if len(removed) != 0 {
		t.Fatalf("the user's file was removed: %v", removed)
	}
	if len(leftovers) != 1 || leftovers[0] != path {
		t.Fatalf("the refusal must name the path so it can be dealt with, got %v", leftovers)
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("the file is gone: %v", err)
	}
}

func TestAGeneratedFileIsRefreshedAndStillOwned(t *testing.T) {
	// The same rule must not make re-install impossible: a file we generated is
	// recognisable, and refreshing it is the whole point of installing again.
	root := t.TempDir()
	path := filepath.Join(root, "AGENTS.md")

	first, err := WriteManaged(path, Marked("# first\n"))
	if err != nil {
		t.Fatal(err)
	}
	if !first.Written || !first.Owned {
		t.Fatalf("a first write must be written and owned: %+v", first)
	}
	second, err := WriteManaged(path, Marked("# second\n"))
	if err != nil {
		t.Fatal(err)
	}
	if !second.Written || !second.Owned {
		t.Fatalf("a managed file must be refreshable: %+v", second)
	}
	got, _ := os.ReadFile(path)
	if !strings.Contains(string(got), "second") || !strings.Contains(string(got), GeneratedMarker) {
		t.Fatalf("content = %q", got)
	}
}

func TestAnIdenticalFileIsAdoptedRatherThanRefused(t *testing.T) {
	// A user who committed exactly what we would have written should not be told
	// their file was skipped; there is nothing to protect.
	root := t.TempDir()
	path := filepath.Join(root, "AGENTS.md")
	content := Marked("# same\n")
	write(t, path, content)

	result, err := WriteManaged(path, content)
	if err != nil {
		t.Fatal(err)
	}
	if result.Skipped != nil {
		t.Error("an identical file should not be reported as a conflict")
	}
	if !result.Owned {
		t.Error("an identical file should be adopted")
	}
}

func TestAFileInsideAFrameworkDirectoryIsOurs(t *testing.T) {
	// JSON cannot carry the marker without becoming unparseable, so ownership for
	// the connector's own dot-directory rests on the namespace. Without this the
	// uninstall would leave every generated config behind.
	home := t.TempDir()
	root := t.TempDir()
	path := filepath.Join(root, ".opencode", "opencode.json")
	write(t, path, `{"version":1}`)

	removed, leftovers := RemoveManagedPaths(home, []string{path})
	if len(removed) != 1 || len(leftovers) != 0 {
		t.Fatalf("a file in a framework directory must be removed: %v %v", removed, leftovers)
	}
}

func TestAUsersFileInAnUnrelatedDirectoryIsNotOurs(t *testing.T) {
	// "Has a directory component" is not ownership. A project directory the user
	// chose must survive even though its file is named in a manifest.
	home := t.TempDir()
	root := t.TempDir()
	path := filepath.Join(root, ".ai", "goal.json")
	write(t, path, `{"goal":"mine"}`)

	removed, _ := RemoveManagedPaths(home, []string{path})
	if len(removed) != 0 {
		t.Fatalf("a file in a user directory was removed: %v", removed)
	}
}

func TestAPopulatedDirectoryIsNotRemoved(t *testing.T) {
	home := t.TempDir()
	root := t.TempDir()
	dir := filepath.Join(root, ".opencode", "agents")
	write(t, filepath.Join(dir, "architect.md"), "x")

	removed, leftovers := RemoveManagedPaths(home, []string{dir})
	if len(removed) != 0 {
		t.Fatalf("a populated directory was removed: %v", removed)
	}
	if len(leftovers) != 1 {
		t.Fatalf("a populated directory must be reported as a leftover, got %v", leftovers)
	}
}

func TestMarkedLeavesJSONAlone(t *testing.T) {
	// The marker is an HTML comment, legal in Markdown and nowhere else. Putting
	// it in a .json file produces a document no parser reads, and the first
	// version did exactly that — failing connector validation on every generated
	// file with "invalid JSON".
	document := `{"key":"value"}`
	if got := Marked(document); got != document {
		t.Fatalf("JSON was altered: %q", got)
	}
	markdown := "# Title\n"
	if got := Marked(markdown); !strings.Contains(got, GeneratedMarker) {
		t.Fatalf("Markdown was not marked: %q", got)
	}
	if !IsManaged([]byte(Marked(markdown))) {
		t.Error("a marked markdown file must be recognisable as ours")
	}
}

func TestWritingIsAtomicSoAPartialFileIsNeverLeftBehind(t *testing.T) {
	// An agent reads these files. A write interrupted halfway leaves a truncated
	// instructions file that the agent will follow as though it were complete.
	root := t.TempDir()
	path := filepath.Join(root, "nested", "AGENTS.md")
	result, err := WriteManaged(path, Marked("# content\n"))
	if err != nil {
		t.Fatal(err)
	}
	if !result.Written {
		t.Fatal("not written")
	}
	entries, err := os.ReadDir(filepath.Dir(path))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		t.Fatalf("the temp file was left behind: %v", entries)
	}
}
